name: Test Artifact Upload

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create a test file
        run: echo "Hello, world!" > test.txt

      - name: Upload test file
        uses: actions/upload-artifact@v3
        with:
          name: test-artifact
          path: test.txt
