name: Build Linux Binary with Nuitka

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12  # Ou votre version de Python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nuitka

      - name: Build binary with Nuitka
        run: nuitka --standalone --file-description="ModsUpdater for Vintage Story" --follow-imports --windows-icon-from-ico=vintagestory.ico --file-version=2.0.1.1002 --copyright=Laerinok --product-name=ModsUpdater --lto=auto --output-filename=VS_ModsUpdater main.py

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: linux-binary
          path: VS_ModsUpdater
