name: Debug macOS Build

on:
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  build_macos:
    name: Build DMG (macOS)
    runs-on: macos-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build the DMG
        run: python setup.py bdist_dmg

      - name: Upload macOS DMG artifact
        uses: actions/upload-artifact@v4
        with:
          name: VS_ModsUpdater-macOS-Debug
          path: dist/*.dmg
